# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aMTMsample <- function(target, N, d, K, x0, sig0, mu0, lam0, adapt, global, scale, local, proposal, accrate, gamma, parms, beta) {
    .Call('_aMTM_aMTMsample', PACKAGE = 'aMTM', target, N, d, K, x0, sig0, mu0, lam0, adapt, global, scale, local, proposal, accrate, gamma, parms, beta)
}

